# Generated by Django 3.2.18 on 2023-10-21 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='feedback_link',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
